blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    #根据设计需求， 总共有6个页面要实现
    path('', views.index, name='index'),#网站首页
    path('blog/', views.blog, name='blog'),
    path('diary/', views.diary, name= 'diary'),
    path('list-<int:lid>.html', views.list, name='list'),  # 分类列表页
    path('show-<int:sid>.html', views.show, name='show'),  # 内容页
    path('tag/<tag>', views.tag, name='tag'),  # 标签列表页
    path('s/', views.search, name='search'),  # 搜索列表页
    path('about/', views.about, name='about'),  # 联系我们单页
]

comment/urls.py
from django.conf.urls import url
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('upload_comment/', views.upload_comment, name="upload_comment"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),  #登录页面
    path('register/', views.register, name='register'), #注册页面
    path('logout/',views.logout, name='logout'), #登出
    path('user_info/', views.user_info, name='user_info'), #用户信息
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
from django.contrib.contenttypes.fields import GenericRelation
from read_no_count.models import ReadNumExpandMethod,ReadDetail

# Create your models here.

class Category(models.Model):
    name = models.CharField('博客分类', max_length=100)
    index = models.IntegerField(default=1, verbose_name='分类')
    excerpt = models.TextField('摘要', max_length=200, blank=True,null=True)
    img = models.ImageField(upload_to='category_img/%Y/%m/%d/', verbose_name='首页分类图片', blank=True, null=True)

    class Meta:
        #这是后台admin会显示的名字
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=100)
    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#推荐位
class Tui(models.Model):
    name = models.CharField('推荐位',max_length=100)

    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#文章
#继承了类ReadNumExpanMethod内的方法views,才可以在后台的 文章 内显示浏览数！
class Article(models.Model, ReadNumExpandMethod):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)
    #使用外键关联分类表与分类是一对多关系，可以为blank
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类', blank=True)
    #使用外键关联标签表与标签是多对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)


    img = models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片   ',blank=True,null=True)
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    # body = models.TextField()     #通过以下富文本编辑器(百度的)来更好的添加文本
    content = UEditorField('内容', width=800, height=700,toolbars='full', imagePath='upimg/',filePath='upfile/',
                        upload_settings={'imageMaxSize': 1204000},
                        settings={}, command=None, blank=True)
    """
        留意里面的imagePath="upimg/", filePath="upfile/" 这两个是图片和文件上传的路径，
        我们上传文件，会自动上传到项目根目录media文件夹下对应的upimg和upfile目录里，
        这个目录名可以自行定义。有的人问，为什么会上传到media目录里去呢？那是因为之前我们在基础配置文章里，
        设置了上传文件目录media。
    """

    #外键，文章作者关联用户模型，系统自带的
    """
         文章作者，这里User是从django.contrib.auth.models导入的。
         专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
         这里我们通过 ForeignKey 把文章和 User 关联了起来。
         因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    """
    auther = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')


    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)

    created_time = models.DateTimeField('发布时间', auto_now_add=True)  #创建时间，用来标识这条记录的创建时间，具有auto_now_add属性，创建记录时会自动填充当前时间到此字段
    modified_time = models.DateTimeField('修改时间', auto_now=True)     #修改时间，用来标识这条记录最后一次的修改时间，具有auto_now属性，当记录发生变化时填充当前时间到此字段

    # 通过GenericRelation来跟另外一个app内的模型model建立关系！
    read_details = GenericRelation(ReadDetail)



    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Article, Category, Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from read_no_count.utils import read_no_count_once_read, get_seven_days_read_data,get_allTime_hot_data

# Create your views here.

# 右侧aside栏
# def global_variable(request):
#     # 置顶推荐
#     tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3] #拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
#     #热门十篇文章
#     hot = Article.objects.all().order_by('views')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
#     # 文章分类
#     allcategory = Category.objects.all()
#     # 文章标签
#     tags = Tag.objects.all()
#     return locals()


# 首页
def index(request):
    allcategory = Category.objects.filter(index=1).order_by("-id")[0:3]
    allarticle = Article.objects.all().order_by('-id')[0:3]

    dates, read_nums = get_seven_days_read_data(Article)  #用来统计过去七天每天的流量

    return render(request, 'index.html', locals())



def blog(request):
    Allarticle = Article.objects.exclude(category__name__icontains='日记').order_by('-id')  # ---最新文章：中间10篇文章
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()# 文章分类
    tags = Tag.objects.all()# 文章标签

    hot = get_allTime_hot_data(Article)  #返回一堆QuerySet【<ReadNum: ReadNum object (1)>, <ReadNum: ReadNum object (2)>。。。等， 就是后台--浏览--模型内的所有！1】


    page =request.GET.get("page")  #在网址中获取page的参数值
    paginator = Paginator(Allarticle,10)   #10篇翻一页
    try:
        allarticle = paginator.page(page)   # 获取当前页码的记录
    except PageNotAnInteger:
        allarticle = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        allarticle = paginator.page(paginator.num_pages) # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'blog.html', locals())



def list(request, lid):
    List = Article.objects.filter(category_id=lid).order_by('-id') # 获取通过URL传进来的lid，然后筛选出对应分类id的文章
    category_name = Category.objects.get(id=lid) # 获取当前文章的分类名
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签


    hot = get_allTime_hot_data(Article)



    page = request.GET.get('page')  # 在网址URL中获取当前页面数
    paginator = Paginator(List, 10)  # 对查询到的数据对象list进行分页，设置超过5条数据就分页
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'list.html',locals())



def show(request, sid):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签
    interestTopic = Article.objects.all().order_by('?')[0:5]  # 内容下面的您可能感兴趣的文章，随机推荐
    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    show = Article.objects.get(id=sid)  # 查询指定ID的文章-----找到对应内容的文章
    previous_blog = Article.objects.filter(created_time__gt=show.created_time,
                                           category=show.category.id).first()  # create time大于本文的定义为上一篇
    netx_blog = Article.objects.filter(created_time__lt=show.created_time,
                                       category=show.category.id).last()  # 小于本文的定义为下一篇。  category=show.category.id，则是指定查询的文章为  当前分类下  的文章。

    #阅读量方法函数的引入和使用
    read_coockie_key = read_no_count_once_read(request,show)  #这返回的是一个key， 计算文章的总阅读量

    response = render(request, 'show.html',locals())
    response.set_cookie(read_coockie_key,'true')
    return response



def tag(request, tag):
    List = Article.objects.filter(tags__name=tag).order_by('-id') # 通过文章标签进行查询文章--提取对应tag的文章
    tag_name = Tag.objects.get(name=tag) # 返回当前搜索的标签的标签名
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签

    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    page = request.GET.get('page')
    # tags = Tag.objects.all()
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'tag.html', locals())



def search(request):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签

    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    ss = request.GET.get('search')  # 获取搜索的关键词
    List = Article.objects.filter(title__icontains=ss)  # 获取到搜索关键词通过标题进行匹配---找到对应的搜索文章

    page = request.GET.get('page')
    # tags = Tag.objects.all()
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'search.html',locals())



def diary(request):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by("-views()")[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签

    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    List = Article.objects.filter(category__name='日记').order_by('-id')

    page = request.GET.get('page')
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'diary.html',locals())



def about(request):
    return render(request, 'about.html',locals())

templates/base.html
{% load static %}

<!DOCTYPE HTML
<html>

<head>
    <meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Author" content="禾斗">
	<title>禾斗的小博客</title>
	<meta name="description" content="这是禾斗的博客啊" />
	<meta name="keywords" content="技术，博客，知识分享，互联网，前端，后端，网站" />

    <link rel='stylesheet' id='bootstrap-css' href='{% static "css/bootstrap.min.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='fontawesome-css' href='{% static "css/font-awesome.min.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='stylesheet-css' href='{% static "css/style.css" %}' type='text/css' media='all' />
    <link rel='stylesheet' id='raxus-css' href='{% static "css/raxus.css" %}'  type='text/css' media='all' />
    <link rel='stylesheet' id='open-social-style-css' href='{% static "css/os.css" %}' type='text/css' media='all' />
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
    <meta name='robots' content='index,follow' />
    {% block head %}
    {% endblock %}
</head>

<body class="home blog site-layout-2">

    <!-- 头部 -->
    <header class="fix-wrap" id="fix-wrap">
        <div class="fix-main clearfix pr" id="fix-main" _hover-ignore="1"> <a href="/" class="index-logo">
                <img class="myicon" src='{% static "images/icon.jpg" %}' alt="头像"> <img class="mylogo" src='{% static "images/mine.png" %}'
                    alt="禾斗的博客的logo"></a>

            <nav class="nav fl">
                <ul id="fix-list" class="fix-list clearfix">

                    <li id="menu-item-24086" class="menu-item"><a href="/">首页</a></li>

                    <li id="menu-item-117720" class="menu-item">
                        <a href="/blog/">个人博客</a></li>

                    <li id="menu-item-117720" class="menu-item">
                        <a href="/diary/">日记</a></li>

                    <li id="menu-item-24086" class="menu-item"><a href="/about/">关于</a></li>

                    <!-- <li id="menu-item-24086" class="menu-item"><a href="/about/">友链</a></li> -->
                </ul>
            </nav>

            <form method="get" class="index-search  hidden-xs" action="{% url 'blog:search' %}">
                <input class="text" name="search" type="text" placeholder="亲！你想搜啥" value=""><button class="submit" type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>


        <div>
            <ul class="nav navbar-nav navbar-right" style="position: absolute; right: 20px;top: 7px">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a></li>
                    <li><a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a></li>
                {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'user:user_info' %}">个人资料</a></li>
{#                            <li role="separator" class="divider"></li>#}
                            <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a></li>
                       </ul>
                    </li>
                {% endif %}
            </ul>
        </div>

    </header>







    {% block content %}
    {% endblock %}







    <!-- 底部 -->
    <footer class="footer">
        <div class="copyright"> © 2020 - future · KH - All Rights Reserved
            · <a href="/">禾斗的博客</a>
            · <a href="http://www.miibeian.gov.cn" target="_blank">湘ICP备17023990号</a> 版权所有 © 禾斗的博客</div>
    </footer>



    <script type="text/javascript" src="{% static 'js/view-history.js' %}"></script>
    <script type='text/javascript' src='{% static 'js/jquery.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'js/bootstrap.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'js/raxus-slider.min.js' %}'></script>
    <script type='text/javascript' src='{% static 'js/loader.js' %}'></script>
    <script type='text/javascript' src='{% static 'js/bj-lazy-load.min.js'%}'></script>
    <script type='text/javascript' src='{% static 'js/os.js'%}'></script>

    {% block script_extends %}
    {% endblock %}
</body>

</html>

templates/error.html
{% extends 'base.html' %}
{% block content %}

<div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);color: #00a0e9; font-size: 3em">
    {{ message }}, <a href="{{ redirect_to }}">返回</a>
</div>

{% endblock %}

templates/show.html
{% extends "base.html" %}
{% load static %}
{% load comment_tags %}

{% block head %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block content %}

    <!-- /主体 -->
    <div id="main-container" class="container clearfix">
        <section class="post-left">
            <div class="breadcrumb">您的位置： <a itemprop="breadcrumb" href="/">首页</a> » <a href="{% url 'blog:index' %}list-{{ show.category_id }}.html">{{ show.category.name }}</a> »
                <span class="current">正文</div>
            <div class="post-main clearfix">
                <h1 class="post-title">{{ show.title }}</h1>
                <div class="post-con clearfix">
                    <div class="article-meta">
                        <span class="item">分类：<a href="{% url 'blog:index' %}list-{{ show.category_id }}.html" rel="category tag">{{ show.category.name }}</a></span>
                        <span class="item">作者：{{ show.auther }}</span>
                        <span class="item">{{ show.created_time }}</span>
                        <span class="item">阅读：{{ show.views }}</span>
                        <span class="item">评论：{% get_comment_count show %}</span>

                    </div>
                    <article class="article-content">
                    {{ show.content|safe }}
                    </article>

                    <div class="post-tag"><span class="fa fa-tags" aria-hidden="true"></span>标签：

                        {% for tag in show.tags.all %}
                            <a href="{% url 'blog:index' %}tag/{{ tag.name }}" rel="tag">{{ tag.name }}</a>
                        {% endfor %}

                    </div>
                    <div>
                        <div><b>上一篇：</b>
                            {% if netx_blog %}
                                <a href="/show-{{ netx_blog.pk }}.html" class="article-tag">{{ netx_blog }}</a>
                            {% else %}
                                没有了
                            {% endif %}

                        </div>
                        <div><b>下一篇：</b>

                            {% if previous_blog %}
                                <a href="show-{{ previous_blog.pk }}.html" class="article-tag">{{ previous_blog }}</a>
                            {% else %}
                                没有了
                            {% endif %}


                        </div>
                    </div>
                </div>

            </div>
            <!-- /文章 -->

            <!-- 你可能感兴趣的文章 -->
            <div class="recommend  hidden-xs">

                <div class="head clearfix"><span class="sp">您可能感兴趣的:</span></div>
                <ul>

                    {% for h in interestTopic %}
                    <li>
                     <div class="pic">
                       <a href="{% url 'blog:index' %}show-{{ h.id }}.html" title="{{ h.title }}">
                       <img src="{% url 'blog:index' %}media/{{ h.img }}"
                         srcset="{% url 'blog:index' %}media/{{ h.img }}"
                         alt="{{ h.title }}" class="wp-post-image" width="145" height="100"/></a>
                      </div>
                        <a class="descript " href="{% url 'blog:index' %}show-{{ h.id }}.html" rel="bookmark"
                               title="{{ h.title }}">{{ h.title }}</a>
                    </li>
                    {% endfor %}

                </ul>
            </div>

            <div class="comment">
                <div class="head clearfix head_top">
                    <span class="sp">评论列表:</span>
                    <a class="want_comment" href="javascript:want_comment();"><button class="btn btn-info pull-right">我要评论</button></a>
                </div>
                    <div class="comment-area" style="margin: 0 20px">
                        <div id="comment_list">
                            {% get_comment_list show as comments %}
                            {% for com in comments %}
                                <div id="root_{{ com.pk }}" class="comment">
                                    <span class="user">{{ com.user.username }}:</span>
                                    <div id="comment_{{ com.pk }}" class="content_word">
                                        {{ com.comment_text|safe }}
                                    </div>
                                    <div style="text-align: right">
                                        <span>{{ com.comment_time |date:'Y年m月d日 H:i:s' }} </span>
                                        <a href="javascript:reply({{ com.pk }});">回复</a>
                                    </div>



                                    {% for reply in com.root_comment.all %}
                                        <div class="reply">
                                            <div class="user">
                                                <span>{{ reply.user.username }}</span>
                                                <span>回复</span>
                                                <span>{{ reply.reply_to.username }}: </span>
                                            </div>
                                            <div id="comment_{{ reply.pk }}" class="content_word">
                                                {{ reply.comment_text|safe }}
                                            </div>
                                            <div style="text-align: right">
                                                <span>{{ reply.comment_time |date:'Y年m月d日 H:i:s' }}</span>
                                                <a href="javascript:reply({{ reply.pk }});">回复</a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% empty %}
                                <span id="no_comment">暂无评论</span>
                            {% endfor %}
                        </div>


                    </div>

                    <div class="head clearfix head_top head_down"><span class="sp">新的评论:</span></div>
                    <div class="comment-area new-comment" style="margin: 0 20px">

                        {% if user.is_authenticated %}
                            <form id="comment_form" action="{% url 'comment:upload_comment' %}" method="post" style="overflow: hidden">
                                <label>{{ user.username }},欢迎评论~</label>
                                <div id="reply_content_container" style="display: none">
                                    <p>回复：</p>
                                    <div id="reply_content"></div>
                                </div>
                                {% csrf_token %}
                                {% get_comment_from show %}
                                <span id="comment_error" class="text-danger pull-left"></span>
                                <a href="javascript:clear_data();" class="btn btn-default pull-right comment_upload">清空</a>
                                <input type="submit" value="提交" class="btn btn-info pull-right comment_upload">
                            </form>
                        {% else %}
                            您尚未登录，登录后方可评论~
                            <a class="btn btn-primary" href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a>
                            <span> or </span>
                            <a class="btn btn-danger" href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a>
                        {% endif %}
                    </div>

            </div>

        </section>




       {% include "right.html" %}


    </div>
    <!-- /主体 -->

{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#comment_form").submit(function() {
            //判断评论框是否为空
            $('#comment_error').text('');
            if(CKEDITOR.instances["id_comment_text"].document.getBody().getText().trim()==''){
                $('#comment_error').text('评论内容不能为空');
                return false;
            }

            //更新数据到textarea
            CKEDITOR.instances["id_comment_text"].updateElement();
            //异步提交，使用ajax技术
            $.ajax({
                url: '{% url 'comment:upload_comment' %}',
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data) {
                    console.log(data);
                    if (data['status'] == 'SUCCESS'){
                        if($('#reply_comment_id').val()=='0'){
                            //插入评论
                            var comment_html = '<div id="root_' + data['pk'] +'" class="comment"><span class="user">' + data['username'] + '</span><div class="content_word" id="comment_'+ data['pk'] +'">'+ data['comment_text'] + '</div><div style="text-align: right"><span> ' + data['comment_time'] +' </span><a href="javascript:reply('+ data['pk'] + ');">回复</a></div>';
                            $('#comment_list').prepend(comment_html);

                        }else {
                            //插入回复
                            var reply_html =  '<div class="reply"><div class="user"><span>' + data['username'] + '</span><span> 回复 </span><span>'+ data['reply_to'] +': </span></div><div class="content_word" id="comment_'+ data['pk'] +'">'+ data['comment_text'] +'</div><div style="text-align: right"><span> '+ data['comment_time'] +'</span><a href="javascript:reply('+ data['pk'] +');">回复</a></div></div>';
                            $("#root_" + data['root_pk']).append(reply_html);
                        };

                        //插入评论数据后，清空评论框的内容
                        CKEDITOR.instances["id_comment_text"].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                        $('#comment_error').text('评论成功');

                    }else {
                        //显示错误信息
                        $('#comment_error').text(data['message']);
                    }

                },
                error: function (xhr) {
                    console.log(xhr);
                }
            });
            return false;
        });
        function reply(reply_comment_id) {
            //设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html = $('#comment_' + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();

            $('body').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function() {
                CKEDITOR.instances['id_comment_text'].focus();
            });
        };
        function want_comment() {
            $('body').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function() {
                CKEDITOR.instances['id_comment_text'].focus();
            });
        };
        function clear_data() {
            if(CKEDITOR.instances["id_comment_text"].document.getBody().getText().trim() !='') {
                CKEDITOR.instances["id_comment_text"].setData('');
            }
        };
        /*
        function numFormat(num) {
            return ('00' + num).substr(-2);
        }
        function timeFormat(timestamp) {
            var datetime = new Date(timestamp * 1000);
            var year = datetime.getFullYear();
            var month = numFormat(datetime.getMonth() + 1);
            var day = numFormat(datetime.getDay()+2);
            var hour = numFormat(datetime.getHours());
            var minute = numFormat(datetime.getMinutes());
            var second = numFormat(datetime.getSeconds());
            return year+'-'+month+'-'+day+' '+hour+':'+minute+':'+second;
        }
         */
    </script>
{% endblock %}